name: flutter_embedding_cli
description: This project helps generating modules for embedding flutter into a native ios, android or react-native app.
version: 0.0.1-beta.5

homepage: https://github.com/krispypen/flutter_embedding
repository: https://github.com/krispypen/flutter_embedding/tree/main/packages/flutter_embedding_cli
issue_tracker: https://github.com/krispypen/flutter_embedding/labels/flutter_embedding_cli

topics:
  - cli
  - embedding-flutter
  - embedding-ios
  - embedding-android
  - embedding-react-native

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.5.0
  path: ^1.8.3
  mason: ^0.1.1
  yaml: ^3.0.0
  xcodeproj: ^0.2.4+2

dev_dependencies:
  lints: ^6.0.0


